### ISSUE TITLE
Uncaught TypeError: Cannot read property 'statuses' of null

### ISSUE THREAD

**Issue by tjbenton** [hmatsuda/open-git-modified-files#3]
[Enter steps to reproduce below:]
1. If I have a folder open in an atom window that isn't a git project it throws an error. Folders that aren't git projects just need to be ignored. 

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.4
**Thrown From**: [open-git-modified-files](https://github.com/hmatsuda/open-git-modified-files) package, v0.2.0
### Stack Trace

Uncaught TypeError: Cannot read property 'statuses' of null

```
At /Users/tylerbenton/.atom/packages/open-git-modified-files/lib/open-git-modified-files.coffee:19

TypeError: Cannot read property 'statuses' of null
  at /Users/tylerbenton/.atom/packages/open-git-modified-files/lib/open-git-modified-files.coffee:19:9
  at Object.module.exports.open (/Users/tylerbenton/.atom/packages/open-git-modified-files/lib/open-git-modified-files.coffee:43:13)
  at atom-workspace.subscriptions.add.atom.commands.add.open-git-modified-files:open (/Users/tylerbenton/.atom/packages/open-git-modified-files/lib/open-git-modified-files.coffee:10:43)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
  2x -1:05.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  3x -1:02.6.0 core:move-left (atom-text-editor.editor.mini.is-focused)
     -1:00.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:59.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.mini.is-focused)
     -0:59.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:56.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:36.7.0 core:cancel (atom-pane.pane.active)
     -0:35.1.0 command-palette:toggle (atom-pane.pane.active)
     -0:32.4.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:30.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:30.2.0 open-git-modified-files:open (atom-pane.pane.active)
     -0:21.2.0 core:close (atom-text-editor.editor.is-focused)
     -0:15.5.0 command-palette:toggle (atom-pane.pane.active)
  2x -0:13.6.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:05.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.4.0 open-git-modified-files:open (atom-pane.pane.active)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "oceanic-next"
    ],
    "ignoredNames": [
      ".git",
      ".sass-cache/",
      ".DS_Store",
      ".subl*.tmp"
    ],
    "disabledPackages": [
      "es-navigation",
      "remember-session",
      "terminal-status",
      "linter-scss-lint",
      "highlight-selected",
      "react"
    ],
    "audioBeep": false
  }
}
```
### Installed Packages

``` coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
Stylus, v1.1.0
Sublime-Style-Column-Selection, v1.3.0
atom-material-ui, v0.5.21
atom-pair, v2.0.5
auto-update-packages, v1.0.0
change-case, v0.6.0
docblockr, v0.7.3
emmet, v2.3.12
enhanced-package-list, v1.0.3
file-icons, v1.6.5
fold-comments, v0.5.0
fold-functions, v0.3.1
git-diff-details, v0.20.0
hyperclick, v0.0.30
iTunes, v0.2.0
language-SCSS, v0.4.0
language-babel, v0.11.8
language-cfml, v0.8.8
language-coldfusion, v0.2.0
language-javascript-jsx, v0.3.7
linter, v1.4.2
linter-jscs, v2.0.4
oceanic-next, v0.1.2
open-git-modified-files, v0.2.0
preview-plus, v1.2.6
styleguide, v0.44.0
white-cursor, v0.6.0

# Dev
No dev packages
```

**Comment by hmatsuda** [comment]
@tjbenton Thanks for reporting. I published v0.2.1 without this issue.
